#!/bin/sh
# Give dmenu list of all android emulators to run.
# Shows the selected android device in dunst if running.

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

chosen=$(/opt/android-sdk/emulator/emulator -list-avds | rofi -width 25 -columns 1 -dmenu -i -p "Choose Android emulator to run")

[ "$chosen" != "" ] || exit

s=$(echo "$chosen" | sed "s/ .*//")
notify-send " $s runned!" &
echo "$s" | tr -d '\n' | /opt/android-sdk/emulator/emulator -avd $s
